Feat(compute): add web service to collect data for Conservation Strategy  module
PnX-SI/gn_module_flore_prioritaire pull request #41
Opened 2023-01-30 13:17 UTC by ch-cbna

See #40

2023-05-23 10:24 UTC, jpm-cbna requested changes
Il faudrait:
- revoir l'ensemble de ton code pour t'assurer que toutes les variables, méthodes, fonctions, classes... sont bien nommés en anglais.
- faire un petit travail de refactorisation de code.
- mettre à jour la lib `gn_conservation_backend` en v0.5 pour éviter la duplication du code dans le fichier `utils.py`.

2023-05-23 10:24 UTC, jpm-cbna commented on backend/gn_module_priority_flora/utils.py
Plutôt que de mettre ces méthodes ici, il faudrait simplement mettre à jour la dépendance du module à la lib [gn_conservation_backend_shared](https://github.com/cbn-alpin/gn_conservation_backend_shared) vers la version 0.5.

Dans la version 0.5, toutes ces méthodes là sont y sont déjà. Il faut donc ensuite les importer depuis cette lib. Cela évite ainsi de dupliquer le code entre tous les modules.

Tu pourras enfin supprimer ce fichier qui devient inutile normalement.

2023-05-23 10:24 UTC, jpm-cbna commented on backend/gn_module_priority_flora/repositories.py
> +                .filter(cte.c.habitat_favorable.ilike('1'))
Pourquoi utiliser "ilike" ici une simple comparaison ne convient pas ?

2023-05-23 10:24 UTC, jpm-cbna commented on backend/gn_module_priority_flora/repositories.py
> +                func.count(func.distinct(cte.c.id_zp)).label("nb_stations"),
Ici "`stations`" aurait été mieux vu que les autres paramètres ne précise pas "`nbr`" ou "`percent`"... Ou alors, il aurait fallu rajouté le type à chaque fois.

Ceci dit, ici les labels ne semble servir à rien car ensuite tu utilises l'ordre des résultats pour affecter les résultats de la requête à la variable "`calculations`".

2023-05-23 10:24 UTC, jpm-cbna commented on backend/gn_module_priority_flora/repositories.py
> +        query_calculations = (
C'est plutôt un résultat qu'une requête car utilise la fonction `.one()` qui renvoie un résultat. Donc la variable serait mieux nommée "`calculations_result`".

2023-05-23 10:24 UTC, jpm-cbna commented on backend/gn_module_priority_flora/repositories.py
> +        departement = (
Même si le code qui renvoie cette sous-requête n'est utilisé qu'ici, il serait intéressant de le déplacer dans une méthode privées _get_departements_subquery(). 

Cela permet de clarifier l'action principale de ta méthode `get_prospections()` et en cas de besoin ultérieur cela permet de réutiliser ce code directement.

Tu peux aussi faire de même avec la sous-requête suivante "`observateur`" qui d'ailleurs devrait être nommé en anglais.

2023-05-24 13:16 UTC, ch-cbna commented on backend/gn_module_priority_flora/blueprint.py
> +from .repositories import translate_exported_columns, get_export_headers, StatRepository
les 3 derniers imports concernent le module priority_flora, je les mettrai dans un même bloc.

2023-05-25 08:47 UTC, jpm-cbna commented on backend/gn_module_priority_flora/blueprint.py
> +from geonature.utils.env import db
Non, les flask, alembic et sqlalchemy sont des bibliothèques tiercent. Les lib pythons sont les éléments qui nécessitent des imports et que tu trouvera ici : https://docs.python.org/3/library/
Par exemple `csv`, `datetime`...

2023-05-31 15:36 UTC, ch-cbna commented on backend/gn_module_priority_flora/repositories.py
> +                .filter(cte.c.habitat_favorable.ilike('1'))
il est nécessaire d'utiliser "like" car la comparaison se fait sur cd_nomenclature qui est de type varchar. Le "ilike" n'est pas nécessaire pour un entier.

2023-08-29 15:06 UTC, jpm-cbna requested changes
La librairie "gn_conservation_backend_shared" est bien inclue en v0.5.0 mais le fichier utils qui contient des fonctions de cette librairie est toujours présent...

2023-08-29 15:06 UTC, jpm-cbna commented on backend/gn_module_priority_flora/utils.py
Il me semble que ce fichier est inutile car toutes les fonctions présentes ici sont dans lib partagée "gn_conservation_backend_shared". Il faudrait donc les récupérer depuis la librairie...

2023-10-13 09:21 UTC, jpm-cbna approved these changes

2023-10-13 09:25 UTC, merged